name: Testing
on: push
jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies auth
        run: cd server/auth && yarn
      - name: Install dependencies db
        run: cd server/db && yarn
      - name: Install dependencies frontend
        run: cd public && yarn

      - name: Run coverage auth
        run: cd server/auth && yarn coverage
      - name: Run coverage db
        run: cd server/db && yarn coverage
      - name: Run coverage frontend
        run: cd public && yarn coverage

      - name: Coveralls run
        uses: coverallsapp/github-action@v2
        with:
          files: server/auth/coverage/clover.xml server/db/coverage/clover.xml public/coverage/clover.xml

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: public

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
